runtime: python38
env: standard

entrypoint: gunicorn -b :$PORT app:app

# This example assumes your Flask app is in a folder called "server"
# and your Next.js app is in a folder called "client"
handlers:
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301
    static_dir: server/static

  - url: /(.*\.(js|css|png|jpg|gif|svg|woff|woff2|ttf|eot|ico))$
    static_files: client/\1
    upload: client/.*\.(js|css|png|jpg|gif|svg|woff|woff2|ttf|eot|ico)$

  - url: /.*
    static_files: client/index.html
    upload: client/index.html
